module.exports = [
  { id: 'repubblica', name: 'La Repubblica', url: 'https://www.repubblica.it/rss/homepage/rss2.0.xml', type: 'rss', language: 'it' },
  { id: 'ansa_home', name: 'ANSA - Home', groupId: 'ansa', groupName: 'ANSA', subSource: 'Home', url: 'https://www.ansa.it/sito/ansait_rss.xml', type: 'rss', language: 'it' },
  { id: 'ansa_mondo', name: 'ANSA - Mondo', groupId: 'ansa', groupName: 'ANSA', subSource: 'Mondo', url: 'https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml', type: 'rss', language: 'it' },
  { id: 'ansa_politica', name: 'ANSA - Politica', groupId: 'ansa', groupName: 'ANSA', subSource: 'Politica', url: 'https://www.ansa.it/sito/notizie/politica/politica_rss.xml', type: 'rss', language: 'it' },
  { id: 'ansa_cultura', name: 'ANSA - Cultura', groupId: 'ansa', groupName: 'ANSA', subSource: 'Cultura', url: 'https://www.ansa.it/sito/notizie/cultura/cultura_rss.xml', type: 'rss', language: 'it' },
  { id: 'ansa_scienza', name: 'ANSA - Scienza', groupId: 'ansa', groupName: 'ANSA', subSource: 'Scienza', url: 'https://www.ansa.it/sito/notizie/scienza/scienza_rss.xml', type: 'rss', language: 'it' },
  { id: 'ansa_sport', name: 'ANSA - Sport', groupId: 'ansa', groupName: 'ANSA', subSource: 'Sport', url: 'https://www.ansa.it/sito/notizie/sport/sport_rss.xml', type: 'rss', language: 'it' },
  { id: 'sole24ore_home', name: 'Il Sole 24 Ore - Home', groupId: 'sole24ore', groupName: 'Il Sole 24 Ore', subSource: 'Home', url: 'https://www.ilsole24ore.com/rss/home.xml', type: 'rss', language: 'it' },
  { id: 'sole24ore_economia', name: 'Il Sole 24 Ore - Economia', groupId: 'sole24ore', groupName: 'Il Sole 24 Ore', subSource: 'Economia', url: 'https://www.ilsole24ore.com/rss/economia.xml', type: 'rss', language: 'it' },
  { id: 'sole24ore_finanza', name: 'Il Sole 24 Ore - Finanza e Mercati', groupId: 'sole24ore', groupName: 'Il Sole 24 Ore', subSource: 'Finanza e Mercati', url: 'https://www.ilsole24ore.com/rss/finanza-e-mercati.xml', type: 'rss', language: 'it' },
  { id: 'sole24ore_italia', name: 'Il Sole 24 Ore - Italia', groupId: 'sole24ore', groupName: 'Il Sole 24 Ore', subSource: 'Italia', url: 'https://www.ilsole24ore.com/rss/italia.xml', type: 'rss', language: 'it' },
  { id: 'sole24ore_mondo', name: 'Il Sole 24 Ore - Mondo', groupId: 'sole24ore', groupName: 'Il Sole 24 Ore', subSource: 'Mondo', url: 'https://www.ilsole24ore.com/rss/mondo.xml', type: 'rss', language: 'it' },
  { id: 'genova24', name: 'Genova24', url: 'https://www.genova24.it/feed', type: 'rss', language: 'it' },
  { id: 'ivgsavona', name: 'IVG Savona', url: 'https://www.ivg.it/?feed=news-news24', type: 'rss', language: 'it' },
  { id: 'savonanews', name: 'Savona News', url: 'https://www.savonanews.it/rss.xml', type: 'rss', language: 'it' },
  { id: 'imperiapost', name: 'ImperiaPost', url: 'https://www.imperiapost.it/feed', type: 'rss', language: 'it' },
  { id: 'bbc', name: 'BBC News', url: 'http://feeds.bbci.co.uk/news/world/rss.xml', type: 'rss', language: 'en' },
  { id: 'guardian', name: 'The Guardian', url: 'https://www.theguardian.com/world/rss', type: 'rss', language: 'en' },
  { id: 'lemonde', name: 'Le Monde', url: 'https://www.lemonde.fr/rss/une.xml', type: 'rss', language: 'fr' }
];
